# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/buaa/CLionProjects/marvelCoding

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/buaa/CLionProjects/marvelCoding

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/buaa/CLionProjects/marvelCoding/CMakeFiles /home/buaa/CLionProjects/marvelCoding/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/buaa/CLionProjects/marvelCoding/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named testServer

# Build rule for target.
testServer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testServer
.PHONY : testServer

# fast build rule for target.
testServer/fast:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/build
.PHONY : testServer/fast

#=============================================================================
# Target rules for targets named testClient

# Build rule for target.
testClient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testClient
.PHONY : testClient

# fast build rule for target.
testClient/fast:
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/build
.PHONY : testClient/fast

src/api/api_app.o: src/api/api_app.cpp.o

.PHONY : src/api/api_app.o

# target to build an object file
src/api/api_app.cpp.o:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/api/api_app.cpp.o
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/api/api_app.cpp.o
.PHONY : src/api/api_app.cpp.o

src/api/api_app.i: src/api/api_app.cpp.i

.PHONY : src/api/api_app.i

# target to preprocess a source file
src/api/api_app.cpp.i:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/api/api_app.cpp.i
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/api/api_app.cpp.i
.PHONY : src/api/api_app.cpp.i

src/api/api_app.s: src/api/api_app.cpp.s

.PHONY : src/api/api_app.s

# target to generate assembly for a file
src/api/api_app.cpp.s:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/api/api_app.cpp.s
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/api/api_app.cpp.s
.PHONY : src/api/api_app.cpp.s

src/codec/codec.o: src/codec/codec.cpp.o

.PHONY : src/codec/codec.o

# target to build an object file
src/codec/codec.cpp.o:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/codec/codec.cpp.o
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/codec/codec.cpp.o
.PHONY : src/codec/codec.cpp.o

src/codec/codec.i: src/codec/codec.cpp.i

.PHONY : src/codec/codec.i

# target to preprocess a source file
src/codec/codec.cpp.i:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/codec/codec.cpp.i
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/codec/codec.cpp.i
.PHONY : src/codec/codec.cpp.i

src/codec/codec.s: src/codec/codec.cpp.s

.PHONY : src/codec/codec.s

# target to generate assembly for a file
src/codec/codec.cpp.s:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/codec/codec.cpp.s
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/codec/codec.cpp.s
.PHONY : src/codec/codec.cpp.s

src/codec/gf.o: src/codec/gf.cpp.o

.PHONY : src/codec/gf.o

# target to build an object file
src/codec/gf.cpp.o:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/codec/gf.cpp.o
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/codec/gf.cpp.o
.PHONY : src/codec/gf.cpp.o

src/codec/gf.i: src/codec/gf.cpp.i

.PHONY : src/codec/gf.i

# target to preprocess a source file
src/codec/gf.cpp.i:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/codec/gf.cpp.i
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/codec/gf.cpp.i
.PHONY : src/codec/gf.cpp.i

src/codec/gf.s: src/codec/gf.cpp.s

.PHONY : src/codec/gf.s

# target to generate assembly for a file
src/codec/gf.cpp.s:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/codec/gf.cpp.s
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/codec/gf.cpp.s
.PHONY : src/codec/gf.cpp.s

src/codec/header.o: src/codec/header.cpp.o

.PHONY : src/codec/header.o

# target to build an object file
src/codec/header.cpp.o:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/codec/header.cpp.o
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/codec/header.cpp.o
.PHONY : src/codec/header.cpp.o

src/codec/header.i: src/codec/header.cpp.i

.PHONY : src/codec/header.i

# target to preprocess a source file
src/codec/header.cpp.i:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/codec/header.cpp.i
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/codec/header.cpp.i
.PHONY : src/codec/header.cpp.i

src/codec/header.s: src/codec/header.cpp.s

.PHONY : src/codec/header.s

# target to generate assembly for a file
src/codec/header.cpp.s:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/codec/header.cpp.s
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/codec/header.cpp.s
.PHONY : src/codec/header.cpp.s

src/codec/test_codec.o: src/codec/test_codec.cpp.o

.PHONY : src/codec/test_codec.o

# target to build an object file
src/codec/test_codec.cpp.o:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/codec/test_codec.cpp.o
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/codec/test_codec.cpp.o
.PHONY : src/codec/test_codec.cpp.o

src/codec/test_codec.i: src/codec/test_codec.cpp.i

.PHONY : src/codec/test_codec.i

# target to preprocess a source file
src/codec/test_codec.cpp.i:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/codec/test_codec.cpp.i
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/codec/test_codec.cpp.i
.PHONY : src/codec/test_codec.cpp.i

src/codec/test_codec.s: src/codec/test_codec.cpp.s

.PHONY : src/codec/test_codec.s

# target to generate assembly for a file
src/codec/test_codec.cpp.s:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/codec/test_codec.cpp.s
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/codec/test_codec.cpp.s
.PHONY : src/codec/test_codec.cpp.s

src/exception/marvel_exception.o: src/exception/marvel_exception.cpp.o

.PHONY : src/exception/marvel_exception.o

# target to build an object file
src/exception/marvel_exception.cpp.o:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/exception/marvel_exception.cpp.o
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/exception/marvel_exception.cpp.o
.PHONY : src/exception/marvel_exception.cpp.o

src/exception/marvel_exception.i: src/exception/marvel_exception.cpp.i

.PHONY : src/exception/marvel_exception.i

# target to preprocess a source file
src/exception/marvel_exception.cpp.i:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/exception/marvel_exception.cpp.i
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/exception/marvel_exception.cpp.i
.PHONY : src/exception/marvel_exception.cpp.i

src/exception/marvel_exception.s: src/exception/marvel_exception.cpp.s

.PHONY : src/exception/marvel_exception.s

# target to generate assembly for a file
src/exception/marvel_exception.cpp.s:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/exception/marvel_exception.cpp.s
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/exception/marvel_exception.cpp.s
.PHONY : src/exception/marvel_exception.cpp.s

src/include/debug.o: src/include/debug.cpp.o

.PHONY : src/include/debug.o

# target to build an object file
src/include/debug.cpp.o:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/include/debug.cpp.o
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/include/debug.cpp.o
.PHONY : src/include/debug.cpp.o

src/include/debug.i: src/include/debug.cpp.i

.PHONY : src/include/debug.i

# target to preprocess a source file
src/include/debug.cpp.i:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/include/debug.cpp.i
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/include/debug.cpp.i
.PHONY : src/include/debug.cpp.i

src/include/debug.s: src/include/debug.cpp.s

.PHONY : src/include/debug.s

# target to generate assembly for a file
src/include/debug.cpp.s:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/include/debug.cpp.s
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/include/debug.cpp.s
.PHONY : src/include/debug.cpp.s

src/include/marvel_constant.o: src/include/marvel_constant.cpp.o

.PHONY : src/include/marvel_constant.o

# target to build an object file
src/include/marvel_constant.cpp.o:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/include/marvel_constant.cpp.o
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/include/marvel_constant.cpp.o
.PHONY : src/include/marvel_constant.cpp.o

src/include/marvel_constant.i: src/include/marvel_constant.cpp.i

.PHONY : src/include/marvel_constant.i

# target to preprocess a source file
src/include/marvel_constant.cpp.i:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/include/marvel_constant.cpp.i
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/include/marvel_constant.cpp.i
.PHONY : src/include/marvel_constant.cpp.i

src/include/marvel_constant.s: src/include/marvel_constant.cpp.s

.PHONY : src/include/marvel_constant.s

# target to generate assembly for a file
src/include/marvel_constant.cpp.s:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/include/marvel_constant.cpp.s
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/include/marvel_constant.cpp.s
.PHONY : src/include/marvel_constant.cpp.s

src/include/marvel_log.o: src/include/marvel_log.cpp.o

.PHONY : src/include/marvel_log.o

# target to build an object file
src/include/marvel_log.cpp.o:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/include/marvel_log.cpp.o
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/include/marvel_log.cpp.o
.PHONY : src/include/marvel_log.cpp.o

src/include/marvel_log.i: src/include/marvel_log.cpp.i

.PHONY : src/include/marvel_log.i

# target to preprocess a source file
src/include/marvel_log.cpp.i:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/include/marvel_log.cpp.i
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/include/marvel_log.cpp.i
.PHONY : src/include/marvel_log.cpp.i

src/include/marvel_log.s: src/include/marvel_log.cpp.s

.PHONY : src/include/marvel_log.s

# target to generate assembly for a file
src/include/marvel_log.cpp.s:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/include/marvel_log.cpp.s
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/include/marvel_log.cpp.s
.PHONY : src/include/marvel_log.cpp.s

src/marvel/marvel_app.o: src/marvel/marvel_app.cpp.o

.PHONY : src/marvel/marvel_app.o

# target to build an object file
src/marvel/marvel_app.cpp.o:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/marvel/marvel_app.cpp.o
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/marvel/marvel_app.cpp.o
.PHONY : src/marvel/marvel_app.cpp.o

src/marvel/marvel_app.i: src/marvel/marvel_app.cpp.i

.PHONY : src/marvel/marvel_app.i

# target to preprocess a source file
src/marvel/marvel_app.cpp.i:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/marvel/marvel_app.cpp.i
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/marvel/marvel_app.cpp.i
.PHONY : src/marvel/marvel_app.cpp.i

src/marvel/marvel_app.s: src/marvel/marvel_app.cpp.s

.PHONY : src/marvel/marvel_app.s

# target to generate assembly for a file
src/marvel/marvel_app.cpp.s:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/marvel/marvel_app.cpp.s
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/marvel/marvel_app.cpp.s
.PHONY : src/marvel/marvel_app.cpp.s

src/marvel/marvel_client.o: src/marvel/marvel_client.cpp.o

.PHONY : src/marvel/marvel_client.o

# target to build an object file
src/marvel/marvel_client.cpp.o:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/marvel/marvel_client.cpp.o
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/marvel/marvel_client.cpp.o
.PHONY : src/marvel/marvel_client.cpp.o

src/marvel/marvel_client.i: src/marvel/marvel_client.cpp.i

.PHONY : src/marvel/marvel_client.i

# target to preprocess a source file
src/marvel/marvel_client.cpp.i:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/marvel/marvel_client.cpp.i
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/marvel/marvel_client.cpp.i
.PHONY : src/marvel/marvel_client.cpp.i

src/marvel/marvel_client.s: src/marvel/marvel_client.cpp.s

.PHONY : src/marvel/marvel_client.s

# target to generate assembly for a file
src/marvel/marvel_client.cpp.s:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/marvel/marvel_client.cpp.s
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/marvel/marvel_client.cpp.s
.PHONY : src/marvel/marvel_client.cpp.s

src/marvel/marvel_server.o: src/marvel/marvel_server.cpp.o

.PHONY : src/marvel/marvel_server.o

# target to build an object file
src/marvel/marvel_server.cpp.o:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/marvel/marvel_server.cpp.o
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/marvel/marvel_server.cpp.o
.PHONY : src/marvel/marvel_server.cpp.o

src/marvel/marvel_server.i: src/marvel/marvel_server.cpp.i

.PHONY : src/marvel/marvel_server.i

# target to preprocess a source file
src/marvel/marvel_server.cpp.i:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/marvel/marvel_server.cpp.i
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/marvel/marvel_server.cpp.i
.PHONY : src/marvel/marvel_server.cpp.i

src/marvel/marvel_server.s: src/marvel/marvel_server.cpp.s

.PHONY : src/marvel/marvel_server.s

# target to generate assembly for a file
src/marvel/marvel_server.cpp.s:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/marvel/marvel_server.cpp.s
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/marvel/marvel_server.cpp.s
.PHONY : src/marvel/marvel_server.cpp.s

src/marvel/marvel_socket.o: src/marvel/marvel_socket.cpp.o

.PHONY : src/marvel/marvel_socket.o

# target to build an object file
src/marvel/marvel_socket.cpp.o:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/marvel/marvel_socket.cpp.o
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/marvel/marvel_socket.cpp.o
.PHONY : src/marvel/marvel_socket.cpp.o

src/marvel/marvel_socket.i: src/marvel/marvel_socket.cpp.i

.PHONY : src/marvel/marvel_socket.i

# target to preprocess a source file
src/marvel/marvel_socket.cpp.i:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/marvel/marvel_socket.cpp.i
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/marvel/marvel_socket.cpp.i
.PHONY : src/marvel/marvel_socket.cpp.i

src/marvel/marvel_socket.s: src/marvel/marvel_socket.cpp.s

.PHONY : src/marvel/marvel_socket.s

# target to generate assembly for a file
src/marvel/marvel_socket.cpp.s:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/src/marvel/marvel_socket.cpp.s
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/src/marvel/marvel_socket.cpp.s
.PHONY : src/marvel/marvel_socket.cpp.s

test/test_app.o: test/test_app.cpp.o

.PHONY : test/test_app.o

# target to build an object file
test/test_app.cpp.o:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/test/test_app.cpp.o
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/test/test_app.cpp.o
.PHONY : test/test_app.cpp.o

test/test_app.i: test/test_app.cpp.i

.PHONY : test/test_app.i

# target to preprocess a source file
test/test_app.cpp.i:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/test/test_app.cpp.i
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/test/test_app.cpp.i
.PHONY : test/test_app.cpp.i

test/test_app.s: test/test_app.cpp.s

.PHONY : test/test_app.s

# target to generate assembly for a file
test/test_app.cpp.s:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/test/test_app.cpp.s
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/test/test_app.cpp.s
.PHONY : test/test_app.cpp.s

test/test_client.o: test/test_client.cpp.o

.PHONY : test/test_client.o

# target to build an object file
test/test_client.cpp.o:
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/test/test_client.cpp.o
.PHONY : test/test_client.cpp.o

test/test_client.i: test/test_client.cpp.i

.PHONY : test/test_client.i

# target to preprocess a source file
test/test_client.cpp.i:
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/test/test_client.cpp.i
.PHONY : test/test_client.cpp.i

test/test_client.s: test/test_client.cpp.s

.PHONY : test/test_client.s

# target to generate assembly for a file
test/test_client.cpp.s:
	$(MAKE) -f CMakeFiles/testClient.dir/build.make CMakeFiles/testClient.dir/test/test_client.cpp.s
.PHONY : test/test_client.cpp.s

test/test_server.o: test/test_server.cpp.o

.PHONY : test/test_server.o

# target to build an object file
test/test_server.cpp.o:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/test/test_server.cpp.o
.PHONY : test/test_server.cpp.o

test/test_server.i: test/test_server.cpp.i

.PHONY : test/test_server.i

# target to preprocess a source file
test/test_server.cpp.i:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/test/test_server.cpp.i
.PHONY : test/test_server.cpp.i

test/test_server.s: test/test_server.cpp.s

.PHONY : test/test_server.s

# target to generate assembly for a file
test/test_server.cpp.s:
	$(MAKE) -f CMakeFiles/testServer.dir/build.make CMakeFiles/testServer.dir/test/test_server.cpp.s
.PHONY : test/test_server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... testServer"
	@echo "... testClient"
	@echo "... src/api/api_app.o"
	@echo "... src/api/api_app.i"
	@echo "... src/api/api_app.s"
	@echo "... src/codec/codec.o"
	@echo "... src/codec/codec.i"
	@echo "... src/codec/codec.s"
	@echo "... src/codec/gf.o"
	@echo "... src/codec/gf.i"
	@echo "... src/codec/gf.s"
	@echo "... src/codec/header.o"
	@echo "... src/codec/header.i"
	@echo "... src/codec/header.s"
	@echo "... src/codec/test_codec.o"
	@echo "... src/codec/test_codec.i"
	@echo "... src/codec/test_codec.s"
	@echo "... src/exception/marvel_exception.o"
	@echo "... src/exception/marvel_exception.i"
	@echo "... src/exception/marvel_exception.s"
	@echo "... src/include/debug.o"
	@echo "... src/include/debug.i"
	@echo "... src/include/debug.s"
	@echo "... src/include/marvel_constant.o"
	@echo "... src/include/marvel_constant.i"
	@echo "... src/include/marvel_constant.s"
	@echo "... src/include/marvel_log.o"
	@echo "... src/include/marvel_log.i"
	@echo "... src/include/marvel_log.s"
	@echo "... src/marvel/marvel_app.o"
	@echo "... src/marvel/marvel_app.i"
	@echo "... src/marvel/marvel_app.s"
	@echo "... src/marvel/marvel_client.o"
	@echo "... src/marvel/marvel_client.i"
	@echo "... src/marvel/marvel_client.s"
	@echo "... src/marvel/marvel_server.o"
	@echo "... src/marvel/marvel_server.i"
	@echo "... src/marvel/marvel_server.s"
	@echo "... src/marvel/marvel_socket.o"
	@echo "... src/marvel/marvel_socket.i"
	@echo "... src/marvel/marvel_socket.s"
	@echo "... test/test_app.o"
	@echo "... test/test_app.i"
	@echo "... test/test_app.s"
	@echo "... test/test_client.o"
	@echo "... test/test_client.i"
	@echo "... test/test_client.s"
	@echo "... test/test_server.o"
	@echo "... test/test_server.i"
	@echo "... test/test_server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

